# Generated by Django 6.0.2 on 2026-04-24 11:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='salas_secundarias',
        ),
        migrations.AddField(
            model_name='actividad',
            name='sala_secundaria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actividades_secundaria', to='app_actividades.sala'),
        ),
    ]
