# Generated by Django 6.0.2 on 2026-04-24 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_actividades', '0002_remove_actividad_salas_secundarias_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='sala_secundaria',
        ),
        migrations.AddField(
            model_name='actividad',
            name='salas_secundarias',
            field=models.ManyToManyField(blank=True, related_name='actividades_secundarias', to='app_actividades.sala'),
        ),
    ]
