# Generated by Django 6.0.2 on 2026-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_actividades', '0003_remove_actividad_sala_secundaria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actividad',
            name='horario',
        ),
        migrations.AddField(
            model_name='actividad',
            name='horario_fin',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='horario_inicio',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
